Lesson 2 (#3)
Add DB integraion
---------

Co-authored-by: b1gslick <bigslick1106@gmai.com>

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,22 +1,14 @@
 ---
-name: Test,Build,Deploy,e2e
+name: Test,Build
+
+permissions:
+  contents: read
+  checks: write
+  id-token: write
 
 on: [push]
 
 jobs:
-  lint:
-    name: Lint
-    runs-on: ubuntu-latest
-    steps:
-      - name: Setup | Checkout
-        uses: actions/checkout@v4
-      - name: Setup | Rust
-        uses: ATiltedTree/setup-rust@v1
-        with:
-          rust-version: stable
-          components: clippy
-      - name: Build | Lint
-        run: cargo clippy
   test:
     name: Test
     runs-on: ubuntu-latest
@@ -27,8 +19,11 @@ jobs:
         uses: ATiltedTree/setup-rust@v1
         with:
           rust-version: stable
-      - name: Build | Compile
-        run: cargo test
+          components: clippy
+      - name: Build | Lint | Test
+        run: |
+          cargo clippy
+          cargo test
 
   security-audit:
     name: security-audit
@@ -47,7 +42,9 @@ jobs:
 
   push_to_registry:
     name: Push Docker image to Docker Hub
+    # runs-on: self-hosted
     runs-on: ubuntu-latest
+    timeout-minutes: 180
     needs: [test]
     steps:
       - name: Check out the repo
@@ -58,6 +55,9 @@ jobs:
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
       - name: Extract metadata (tags, labels) for Docker
         id: meta
@@ -84,10 +84,15 @@ jobs:
       - name: run-compose with tests
         uses: isbang/compose-action@v1.5.1
         with:
-          compose-file: "tests/e2e/docker-compose.yml"
+          compose-file: "docker-compose-e2e.yml"
           up-flags: "--abort-on-container-exit"
         env:
           TAG: ${{ github.ref_name }}
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: "**/tests/e2e/report/*.xml"
 
   smoke-performance:
     name: smoke-performance
@@ -96,23 +101,67 @@ jobs:
     steps:
       - name: Check out the repo
         uses: actions/checkout@v4
+      - name: run docker-compose
+        env:
+          TAG: ${{ github.ref_name }}
+          POSTGRES_DB: "schedulerdb"
+          POSTGRES_USER: "scheduler"
+          POSTGRES_PASSWORD: "scheduler"
+        run: docker-compose -f docker-compose-perf.yml up -d
       - name: run-compose with tests
         env:
           TAG: ${{ github.ref_name }}
-        run: cd tests/performance && docker-compose run k6s run /scripts/perf_test.js --quiet
+        run: docker-compose -f docker-compose-perf.yml run k6s run /scripts/perf_test.js --quiet
+
+  one-handredk-rows-test:
+    name: one-handredk-rows-test
+    runs-on: ubuntu-latest
+    needs: [push_to_registry]
+    steps:
+      - name: Check out the repo
+        uses: actions/checkout@v4
+      - name: run empty db test
+        env:
+          TAG: ${{ github.ref_name }}
+        run: docker-compose -f docker-compose-perf-no100k.yml run k6s run /scripts/get_activities.js --quiet
+      - name: tear down
+        env:
+          TAG: ${{ github.ref_name }}
+        run: docker-compose -f docker-compose-perf-no100k.yml down -v
+
+      - name: run 100_000 rows test
+        env:
+          POSTGRES_DB: "schedulerdb"
+          POSTGRES_USER: "scheduler"
+          POSTGRES_PASSWORD: "scheduler"
+          TAG: ${{ github.ref_name }}
+        run: docker-compose -f docker-compose-perf.yml up -d
+      - name: run-compose with tests
+        env:
+          TAG: ${{ github.ref_name }}
+        run: docker-compose -f docker-compose-perf.yml run k6s run /scripts/get_activities.js --quiet
 
   api-security-check:
     name: api-security-check
     runs-on: ubuntu-latest
     needs: [push_to_registry]
     steps:
-      - name: Create network
-        run: docker network create zapnet
+      - name: Check out the repo
+        uses: actions/checkout@v4
 
       - name: Start target
         env:
           TAG: ${{ github.ref_name }}
-        run: docker run -d -p 8080:8080 --network zapnet t1mon1106/scheduler:${TAG}
+        run: docker-compose -f docker-compose.yml up -d
 
-      - name: Run scan
-        run: docker run --user root --network zapnet -v $HOME:/zap/wrk/:rw -t owasp/zap2docker-stable zap-api-scan.py -t http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1):8080/openapi.json -f openapi -r report.html
+      - name: install deps
+        run: pip install wapiti3
+
+      - name: run scanner
+        run: wapiti -u http://localhost:8080 -o report
+
+      - name: store report
+        uses: actions/upload-artifact@v4
+        with:
+          name: wapiti-report
+          path: report/*
